# Generated by Django 5.1.6 on 2025-03-11 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankhome', '0003_account_temporal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='temporal',
        ),
    ]
