# Generated by Django 5.1.7 on 2025-03-14 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankhome', '0004_deposit_transactionlog_withdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='to_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='bankhome.account'),
        ),
    ]
