# Generated by Django 5.1.7 on 2025-03-14 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankhome', '0005_alter_transaction_to_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='to_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='bankhome.account'),
        ),
    ]
