# Generated by Django 5.1.7 on 2025-03-14 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankhome', '0006_alter_transaction_to_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('from_new_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('to_new_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to='bankhome.account')),
                ('to_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to='bankhome.account')),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
